### ISSUE TITLE
when i test user_authenticator_spec.rb show this failure

### ISSUE THREAD

**Issue by kia-kamangar** [driggl/rails-api-complete-guide#1]
Failure/Error: raise AuthenticationError

     UserAuthenticator::AuthenticationError:
       UserAuthenticator::AuthenticationError

**Comment by rubyboy-hub** [comment]
How did you solve the issue?

**Comment by wmorawski** [comment]
@rubyboy-hub are you using `ErrorMapper` in your ApplicationController? If yes make sure that
```ruby
rescue_from UserAuthenticator::AuthenticationError, with: :authentication_error
```
is after the
```ruby
rescue_from ::StandardError, with: ->(e) { handle_error(e) }
```

it worked for me, in the future I will try to handle it with `JsonapiErrorsHandler`
